### ISSUE TITLE
Mount zvol using PVE cluster ZFS pool name

### ISSUE THREAD

**Issue by iGadget** [alexpdp7/ansible-create-proxmox-host#1]
Nice script, thanks for sharing! A small but IMHO significant improvement could be made though.
Currently, you mount the zvol to the LXC via
> -mp0 /mnt/dokku-docker,mp=/var/lib/docker

In my experience, this will break snaphots and migration of the LXC using the PVE webGUI.
To avoid this, maintain the PVE disk naming scheme when creating the zvol (i.e. for LXC 104, 'vm-104-disk-1') and mount it using the PVE cluster ZFS pool name (i.e. 'local-zfs').
Combined this would look like
`-mp0 local-zfs:vm-104-disk-1,mp=/var/lib/docker`
Then snapshots and migration will keep working.

**Comment by alexpdp7** [comment]
Hi @iGadget , thanks a lot for opening this issue! I really appreciate that someone looks at the random stuff I push here.

Unfortunately, I'm likely to rewrite this in the immediate future, and I don't really have the time to test that this works accurately and to document it properly.

However, I think adding some docs like in #2 would be enough if other people stumble into this repo... do you think it's an OK resolution to your issue?
